kind: Service
apiVersion: v1
metadata:
  name: metadataservice
  namespace: project-filespider
spec:
  selector:
    app: metadataservice
  type: ClusterIP
  ports:
  - port:  80
    targetPort:  8002