pipeline {
    agent { label 'docker-host'}
      environment {
        GITHUB_CREDENTIALS = credentials('github-secret-as-username-password')
    }
    stages {
        stage('Code Checkout') {
            steps{
                checkout scm
            }
        }
        stage('Docker Login') {
            steps {
                sh 'echo $GITHUB_CREDENTIALS_PSW | docker login ghcr.io -u $GITHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage('Build Docker Images') {
            stages {
                stage("userservice build"){
                    when { changeset "userservice/**" }
                    steps {
                        sh "cd userservice && mvn clean spring-boot:build-image"
                        sh 'echo pushing package to github container registry...'
                        sh "docker tag ghcr.io/adminseeker/filespider-userservice:latest ghcr.io/adminseeker/filespider-userservice:latest"
                        sh "docker push ghcr.io/adminseeker/filespider-userservice:latest"
                        sh "docker push ghcr.io/adminseeker/filespider-userservice:latest"
                        sh "docker image rm ghcr.io/adminseeker/filespider-userservice:latest ghcr.io/adminseeker/filespider-userservice:latest"
                    }
                }
               
                stage('Notify'){
                    post {
                        always {
                            emailext to: "aravindarali125@gmail.com",
                            subject: "Jenkins Build ${currentBuild.currentResult}: Job ${env.JOB_NAME}",
                            body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}\n More info at: ${env.BUILD_URL}"
                        }
                    }
                }   
            }
        }
    }
    post {
        failure {
            emailext to: "aravindarali125@gmail.com",
            subject: "Jenkins Build ${currentBuild.currentResult}: Job ${env.JOB_NAME}",
            body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}\n More info at: ${env.BUILD_URL}",
            recipientProviders: [[$class: 'DevelopersRecipientProvider']]
        }
    }
}