apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster

metadata:
  name: rabbitmq-cluster
  namespace: logging
spec:
  type: 
  replicas: 2
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  rabbitmq:
          additionalConfig: |
                  log.console.level = info
                  channel_max = 1700
  service:
    type: ClusterIP