spring:
    application:
        name: metadataservice
    profiles:
        active: default
    cloud:
      kubernetes:
        discovery:
          namespaces:
              - project-filespider
          enabled: true
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.3.109:3306/filespider_metadataservice_db
        username: user
        password: password
    rabbitmq:
      host: rabbitmq-cluster.logging.svc.cluster.local
      port: 5672
      username: rabbitmq-user
      password: rabbitmq-user

server:
    port: 8002


management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin-service.logging.svc.cluster.local:9411/api/v2/spans

# eureka:
#   instance:
#     prefer-ip-address: true
#   client:
#     register-with-eureka: true
#     fetch-registry: true
#     service-url:
#       defaultZone: ${EUREKA_URL:http://localhost:8000/eureka/}

info:
  app:
    name: "Metadata Service"
    description: "File Spider Metadata Microservice Application"
    version: "1.0.0"