spring:
    application:
        name: userservice
    profiles:
        active: default
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/filespider_userservice_db
        username: user
        password: password

server:
    port: 8001


