apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
  namespace: project-filespider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      serviceAccountName: sc-k8s-sa
      containers:
        - name: userservice
          image: ghcr.io/adminseeker/filespider-userservice:latest
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
          ports:
          - containerPort: 8001
      imagePullSecrets:
        - name:  container-registry-secret
