kind: Service
apiVersion: v1
metadata:
  name: gatewayservice
  namespace: project-filespider
spec:
  selector:
    app: gatewayservice
  type: ClusterIP
  ports:
  - port:  80
    targetPort:  8090
    