apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-filespider
  namespace: argocd
spec:
  description: Project for FileSpider deployments
  sourceRepos:
    - 'https://github.com/adminseeker/project-filespider.git'
  destinations:
    - namespace: project-filespider
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
