spring:
    application:
        name: gatewayservice
    profiles:
        active: default
    cloud:
        kubernetes:
          discovery:
            namespaces:
              - project-filespider
            enabled: true
        gateway:
            server:
                webflux:
                    routes:
                        - id: authservice
                          uri: lb://authservice
                          predicates:
                            - "Path=/api/v1/auth/**"

                        - id: userservice
                          uri: lb://userservice
                          predicates:
                            - "Path=/api/v1/users/**"
                        
                        - id: metadataservice
                          uri: lb://metadataservice
                          predicates:
                            - "Path=/api/v1/metadata/**"
    rabbitmq:
      host: rabbitmq-cluster.logging.svc.cluster.local
      port: 5672
      username: rabbitmq-user
      password: rabbitmq-user
      

server:
    port: 8090

# eureka:
#   instance:
#     prefer-ip-address: true
#   client:
#     register-with-eureka: true
#     fetch-registry: true
#     service-url:
#       defaultZone: ${EUREKA_URL:http://localhost:8000/eureka/}

management:
    endpoints:
        web:
            exposure:
                include: "*"
    info:
        env:
            enabled: true
    tracing:
        enabled: true
        sampling:
            probability: 1.0
        propagation:
            type: W3C, B3

    zipkin:
        tracing:
            endpoint: http://zipkin-service.logging.svc.cluster.local:9411/api/v2/spans

info:
    app:
        name: "Gateway Service"
        description: "File Spider Gateway Service Microservice Application"
        version: 1.0.0

gateway:
    auth:
        whitelist:
          - /api/v1/auth/login
          - /api/v1/auth/register
          - /api/v1/auth/validate